// Code generated by qtc from "Index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/html/Index.qtpl:1
package html

//line view/html/Index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/html/Index.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/html/Index.qtpl:1
func StreamIndex(qw422016 *qt422016.Writer, body string) {
//line view/html/Index.qtpl:1
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="go-mvc">
    <link 
      rel="preload" 
      href="/css" 
      as="style" 
      onload="
        this.onload = null;
        this.rel = 'stylesheet'
      "
    >
    <noscript>
      <link rel="stylesheet" href="/css">
    </noscript>
    <title>go-mvc</title>
  </head>
  <body>
    `)
//line view/html/Index.qtpl:23
	qw422016.E().S(body)
//line view/html/Index.qtpl:23
	qw422016.N().S(`
  </body>
</html>
`)
//line view/html/Index.qtpl:26
}

//line view/html/Index.qtpl:26
func WriteIndex(qq422016 qtio422016.Writer, body string) {
//line view/html/Index.qtpl:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/html/Index.qtpl:26
	StreamIndex(qw422016, body)
//line view/html/Index.qtpl:26
	qt422016.ReleaseWriter(qw422016)
//line view/html/Index.qtpl:26
}

//line view/html/Index.qtpl:26
func Index(body string) string {
//line view/html/Index.qtpl:26
	qb422016 := qt422016.AcquireByteBuffer()
//line view/html/Index.qtpl:26
	WriteIndex(qb422016, body)
//line view/html/Index.qtpl:26
	qs422016 := string(qb422016.B)
//line view/html/Index.qtpl:26
	qt422016.ReleaseByteBuffer(qb422016)
//line view/html/Index.qtpl:26
	return qs422016
//line view/html/Index.qtpl:26
}
