// Code generated by qtc from "index_style.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/css/index_style.qtpl:1
package css

//line view/css/index_style.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/css/index_style.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/css/index_style.qtpl:1
func StreamIndex_style(qw422016 *qt422016.Writer) {
//line view/css/index_style.qtpl:1
	qw422016.N().S(`
  * {
    padding: 0;
    margin: 0;
    box-sizing: border-box;
  }

  /* Hide scrollbar for IE, Edge and Firefox */
  body {
    -ms-overflow-style: none;
    scrollbar-width: none;
  }

  /* Hide scrollbar for Chrome, Safari and Opera */
  body::-webkit-scrollbar {
    display: none;
  }
`)
//line view/css/index_style.qtpl:18
}

//line view/css/index_style.qtpl:18
func WriteIndex_style(qq422016 qtio422016.Writer) {
//line view/css/index_style.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/css/index_style.qtpl:18
	StreamIndex_style(qw422016)
//line view/css/index_style.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line view/css/index_style.qtpl:18
}

//line view/css/index_style.qtpl:18
func Index_style() string {
//line view/css/index_style.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line view/css/index_style.qtpl:18
	WriteIndex_style(qb422016)
//line view/css/index_style.qtpl:18
	qs422016 := string(qb422016.B)
//line view/css/index_style.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line view/css/index_style.qtpl:18
	return qs422016
//line view/css/index_style.qtpl:18
}
