// Code generated by qtc from "home.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/home.qtpl:1
package view

//line view/home.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/home.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/home.qtpl:1
func StreamHome(qw422016 *qt422016.Writer, meta_description string, title string) {
//line view/home.qtpl:1
	qw422016.N().S(`
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="description" content="`)
//line view/home.qtpl:7
	qw422016.E().S(meta_description)
//line view/home.qtpl:7
	qw422016.N().S(`">
      <title>`)
//line view/home.qtpl:8
	qw422016.E().S(title)
//line view/home.qtpl:8
	qw422016.N().S(`</title>
    </head>
    <body>
      <h2>`)
//line view/home.qtpl:11
	qw422016.E().S(title)
//line view/home.qtpl:11
	qw422016.N().S(`</h2>
    </body>
  </html>
`)
//line view/home.qtpl:14
}

//line view/home.qtpl:14
func WriteHome(qq422016 qtio422016.Writer, meta_description string, title string) {
//line view/home.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/home.qtpl:14
	StreamHome(qw422016, meta_description, title)
//line view/home.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line view/home.qtpl:14
}

//line view/home.qtpl:14
func Home(meta_description string, title string) string {
//line view/home.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line view/home.qtpl:14
	WriteHome(qb422016, meta_description, title)
//line view/home.qtpl:14
	qs422016 := string(qb422016.B)
//line view/home.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line view/home.qtpl:14
	return qs422016
//line view/home.qtpl:14
}
